name: dartbrasil_bot
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Rodrigo Muniz <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  teledart: ^0.0.22

dev_dependencies:
  test: ^1.0.0
